#!/usr/bin/env python3
"""gen_routers.py — canonical skills hub generator (step 2-3).

Reads:  _assignments.json  (name -> top|gov|hub)
        routes_meta.yaml   (hub description / rules / jump / sections)
Does:   git mv <skill>/ -> skills/<hub>/<skill>/ ; git mv SKILL.md -> INSTRUCTIONS.md
        generate skills/<hub>/SKILL.md (frontmatter + index)  for every hub
        refresh registry.json + skills/INDEX.md (replaces the old flat index)

Safety:  --dry-run just reports.  Refuses to run if there are unstaged changes
         in the skills tree (pass --force to override).  Idempotent: skips
         already-collected skills.

Usage:
  python3 _scripts/gen_routers.py --hub references
  python3 _scripts/gen_routers.py            # all hubs
  python3 _scripts/gen_routers.py --only-generate   # generate SKILL.md/index only
"""
import argparse, json, os, re, subprocess, sys, textwrap

# canonical hub root == ~/.agents/skills (the workspace); skills live directly in it.
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
SKILLS = ROOT

def sh(cmd, **kw):
    return subprocess.run(cmd, shell=True, check=True, cwd=ROOT, capture_output=True, text=True, **kw)

def parse_simple_yaml(path):
    """Minimal YAML reader sufficient for routes_meta.yaml (no nested anchors)."""
    import yaml
    with open(path, encoding='utf-8') as f:
        return yaml.safe_load(f)

def fm_name_desc(skilldir):
    md = os.path.join(skilldir, 'SKILL.md')
    if not os.path.isfile(md):
        return None, None
    txt = open(md, encoding='utf-8', errors='replace').read()
    m = re.match(r'^---\s*\n(.*?)\n---', txt, re.S | re.M)
    if not m:
        return None, None
    fm = m.group(1)
    def grab(key):
        mm = re.search(rf'^{key}:\s*(.*?)(?=\n\w+:\s|\Z)', fm, re.S | re.M)
        if not mm: return None
        return re.sub(r'\s+', ' ', mm.group(1).strip())
    return grab('name'), grab('description')

def oneline(desc, n=110):
    if not desc: return ''
    d = re.sub(r'\s+',' ', desc).strip()
    return d if len(d) <= n else d[:n].rsplit(' ', 1)[0] + '…'

def collect(hub, assignments, dry):
    moved, skipped, missing = [], [], []
    for name in assignments[hub]:
        src = os.path.join(SKILLS, name)
        dst = os.path.join(SKILLS, hub, name)
        if os.path.isdir(dst):
            skipped.append(name); continue
        if not os.path.isdir(src) or not os.path.isfile(os.path.join(src, 'SKILL.md')):
            missing.append(name); continue
        if not dry:
            os.makedirs(os.path.join(SKILLS, hub), exist_ok=True)
            sh(f'git mv "{name}" "{hub}/{name}"')
            sh(f'cd "{hub}/{name}" && git mv SKILL.md INSTRUCTIONS.md 2>/dev/null || mv SKILL.md INSTRUCTIONS.md')
            sh(f'git add -A "{hub}/{name}"')
        moved.append(name)
    return moved, skipped, missing

INDEX_HEADER = """# Skills Index — `~/.agents/skills/`
<!-- GENERATED by _scripts/gen_routers.py — edit routes_meta.yaml / <name>/INSTRUCTIONS.md, then re-run; do not edit by hand. -->

用法：需要某项能力时读对应 hub 的 SKILL.md（含子技能索引表），再读 `skills/<hub>/<name>/INSTRUCTIONS.md`。
hub 列表见下方 "Hubs" 段。
"""

def generate(hub, meta, assignments, index_entries):
    dst = os.path.join(SKILLS, hub)
    entries = []
    meta_h = meta.get('hubs', {}).get(hub, {})
    for name in assignments.get(hub, []):
        d = os.path.join(dst, name)
        if not os.path.isdir(d): continue
        im = os.path.join(d, 'INSTRUCTIONS.md')
        if not os.path.isfile(im): continue
        # frontmatter of INSTRUCTIONS still carries original name/description
        txt = open(im, encoding='utf-8', errors='replace').read()
        m = re.match(r'^---\s*\n(.*?)\n---', txt, re.S | re.M)
        desc = None
        if m:
            dm = re.search(r'description:\s*(.*?)(?=\n\w+:\s|\Z)', m.group(1), re.S | re.M)
            if dm: desc = re.sub(r'\s+',' ', dm.group(1).strip())
        entries.append((name, oneline(desc)))
    sections = meta_h.get('sections')
    if sections:
        body = "## 子技能索引\n\n"
        if isinstance(sections, dict):
            items = [(k, v) for k, v in sections.items()]
        else:  # list of [title, members]
            items = [(s[0], s[1]) for s in sections]
        for title, members in items:
            body += f"### {title}\n\n| 子技能 | 说明 |\n|---|---|\n"
            by_name = dict(entries)
            for nm in members:
                body += f"| {nm} | {by_name.get(nm, '(缺失)')} |\n"
            body += "\n"
    else:
        body = "## 子技能索引\n\n| 子技能 | 说明 |\n|---|---|\n"
        for nm, d in entries:
            body += f"| {nm} | {d} |\n"
    parts = ['---\n']
    parts.append(f"name: {hub}\n")
    parts.append(f"description: {re.sub(chr(10),' ',meta_h.get('description',''))}\n")
    parts.append('---\n\n')
    parts.append(f'# {hub} hub\n\n')
    parts.append('## 判据\n')
    for r in meta_h.get('rules', []): parts.append(f'- {r}\n')
    parts.append('\n')
    parts.append(body)
    parts.append('\n## 跳簇规则\n')
    for j in meta_h.get('jump', []): parts.append(f'- {j}\n')
    parts.append('\n## 使用方式\n\n1. 按上表选中子技能；2. 读 `skills/%s/<name>/INSTRUCTIONS.md`；3. 其内部脚本/资源相对该文件所在目录解析。\n' % hub)
    os.makedirs(dst, exist_ok=True)
    with open(os.path.join(dst, 'SKILL.md'), 'w', encoding='utf-8') as f:
        f.write(''.join(parts))
    index_entries['hubs'][hub] = [(nm, d) for nm, d in entries]
    return entries

def refresh_index(assignments, index_entries):
    top = [n for n in assignments['top'] if os.path.isfile(os.path.join(SKILLS, n, 'SKILL.md'))]
    gov = [n for n in assignments['gov'] if os.path.isfile(os.path.join(SKILLS, n, 'SKILL.md'))]
    lines = [INDEX_HEADER, '\n## Top-level（直接可用）\n\n']
    for n in sorted(set(top + gov)):
        nm, desc = fm_name_desc(os.path.join(SKILLS, n)) or (n, '')
        lines.append(f'- **{n}** — {oneline(desc, 130)}\n')
    lines.append('\n## Hubs（路由入口：读其 SKILL.md 看子技能索引表）\n\n')
    for hub in ['research','scientific','references','dev','data-ml','docs-figures','team']:
        h = index_entries['hubs'].get(hub)
        if not h: continue
        lines.append(f'### {hub}（{len(h)} 个子技能）\n\n')
        lines += [f'- {n} — {d}\n' for n, d in h]
        lines.append('\n')
    with open(os.path.join(SKILLS, 'INDEX.md'), 'w', encoding='utf-8') as f:
        f.write(''.join(lines))

def write_registry(assignments, hub_members):
    reg = {'version': 1, 'generated_by': 'gen_routers.py', 'hubs': {}}
    for hub, members in hub_members.items():
        reg['hubs'][hub] = sorted(members)
    reg['top'] = sorted(assignments['top'])
    reg['gov'] = sorted(assignments['gov'])
    with open(os.path.join(ROOT, 'registry.json'), 'w', encoding='utf-8') as f:
        json.dump(reg, f, ensure_ascii=False, indent=2)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--hub', help='only process this hub')
    ap.add_argument('--dry-run', action='store_true')
    ap.add_argument('--only-generate', action='store_true', help='skip moves; just (re)generate hub SKILL.md/INDEX/registry')
    ap.add_argument('--force', action='store_true', help='proceed even with dirty git tree')
    args = ap.parse_args()

    if not args.dry_run and not args.force:
        st = sh('git status --porcelain -- skills/').stdout.strip()
        if st:
            print('refuse: git tree under skills/ has pending changes (override with --force):\n' + st, file=sys.stderr)
            sys.exit(2)

    assignments = json.load(open(os.path.join(ROOT, '_assignments.json'), encoding='utf-8'))
    meta = parse_simple_yaml(os.path.join(ROOT, 'routes_meta.yaml'))
    hubs = [args.hub] if args.hub else ['research','scientific','references','dev','data-ml','docs-figures','team']

    index_entries = {'hubs': {}}
    hub_members = {}
    for hub in hubs:
        if hub not in assignments or not assignments[hub]:
            # team may have no assignments yet (roles go to roles/ dir)
            m = meta.get('hubs', {}).get(hub, {})
            if hub == 'team':
                pass
            else:
                # hub with no assignment entries still generates an (empty) SKILL.md from meta
                pass
        if hub != 'team':
            moved, skipped, missing = collect(hub, assignments, args.dry_run or args.only_generate)
            if not args.dry_run and moved:
                print(f'[{hub}] moved {len(moved)}, skipped {len(skipped)}, missing {missing}')
            if not args.dry_run:
                sh(f'git add -A "{hub}"')
        if not args.dry_run:
            entries = generate(hub, meta, assignments, index_entries)
            hub_members[hub] = [n for n, _ in entries]
        else:
            # dry run: count from disk (top-level or already in hub)
            cnt = 0
            for n in assignments.get(hub, []):
                if os.path.isfile(os.path.join(SKILLS, n, 'SKILL.md')) or os.path.isfile(os.path.join(SKILLS, hub, n, 'INSTRUCTIONS.md')):
                    cnt += 1
            index_entries['hubs'][hub] = [(n, '(dry-run)') for n in assignments.get(hub, [])][:cnt]
            hub_members[hub] = [n for n in assignments.get(hub, [])][:cnt]
            print(f'[dry-run] {hub}: {cnt} skills would be in index')

    if not args.dry_run:
        refresh_index(assignments, index_entries)
        write_registry(assignments, hub_members)
        sh('git add -A skills/INDEX.md registry.json routes_meta.yaml 2>/dev/null || true')
        print('OK: generated hub SKILL.md(s), INDEX.md, registry.json')

if __name__ == '__main__':
    main()
